export const themes = {
    warm: {
        hero: {
            section:
                'relative overflow-hidden bg-[#f4e7d3] px-5 pb-16 pt-28 md:px-8 md:pt-32',
            backgroundWord: 'text-[#e8c7b0]/55',
            badge:
                'inline-flex items-center gap-3 rounded-full border border-[#dfc3aa] bg-[#fbf2e6]/88 px-4 py-2 shadow-[0_10px_28px_rgba(89,57,35,0.08)] backdrop-blur-sm',
            badgeDot: 'bg-[#ef6ca7]',
            badgeText: 'text-[#9a654b]',
            eyebrow: 'text-[#8f6348]',
            heading: 'text-[#3b2416]',
            headingAccent: 'text-[#7a5040]',
            body: 'text-[#5c4030]',
            tag: 'rounded-full border border-[#e0c7b1] bg-[#fff8ee]/85 px-4 py-2 text-sm text-[#5c4030] shadow-[0_12px_26px_rgba(89,57,35,0.07)]',
            primaryCta:
                'rounded-full bg-[#3b2416] px-6 py-3 text-sm text-[#fff6eb] transition duration-300 hover:bg-[#573726]',
            secondaryCta:
                'rounded-full border border-[#9d755b] bg-white/45 px-6 py-3 text-sm text-[#5c4030] transition duration-300 hover:bg-white/70',
            mediaWrap:
                'relative overflow-hidden rounded-4xl border border-[#ebd3bc] bg-[linear-gradient(180deg,#faf0e8_0%,#efd2c0_46%,#cf9175_100%)] p-4 shadow-[0_20px_44px_rgba(89,57,35,0.1)]',
            mediaInner:
                'rounded-[1.7rem] border-4 border-white/80 bg-[radial-gradient(circle_at_top,#fff7f1_0%,#f3dacc_40%,#d29479_100%)] p-3',
            infoCardOne: 'rounded-[1.8rem] bg-[#f1d6d8] p-5 shadow-[0_14px_34px_rgba(89,57,35,0.08)]',
            infoCardTwo: 'rounded-[1.8rem] bg-[#fff7ef]/92 p-5 shadow-[0_14px_34px_rgba(89,57,35,0.08)]',
            infoEyebrow: 'text-[#9d5f47]',
            infoHeading: 'text-[#3b2416]',
            softBlobOne: 'bg-[#f4acc2]/30',
            softBlobTwo: 'bg-[#e7c09b]/28',
            softBlobThree: 'bg-[#efb5c7]/22',
            role: 'Frontend Developer / UI Explorer',
            title: 'Building digital spaces',
            titleLines: ['that feel soft, thoughtful,', 'and beautifully clear.'],
            description:
                "I'm Shagun Gupta, a BCA student and developer who loves creating responsive websites with strong visual balance, gentle color stories, and interfaces people actually enjoy using.",
            cards: [
                'Responsive frontend builds',
                'Clean UI with warm visual detail',
                'Growing full-stack project experience',
            ],
            sideTitle: 'Based In',
            sideValue: 'Uttar Pradesh, India',
            noteTitle: 'Creative Note',
            noteValue:
                'I like interfaces that feel gentle at first glance and sharp on closer look.',
        },
        about: {
            section: 'relative overflow-hidden bg-[#f4e7d3] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-4xl border border-[#d9c0a7] bg-[#f8efe1] p-4 shadow-[0_20px_60px_rgba(89,57,35,0.12)] md:p-6 lg:p-8',
            leftPanel: 'relative rounded-[1.75rem] bg-[#f1d6d8] p-4 md:p-5',
            titleMark: 'text-[#ef6ca7]/70',
            photoFrame: 'relative z-20 mt-48 rounded-3xl border-4 border-white bg-linear-to-br from-[#d7b29d] via-[#f3dfd2] to-[#c88e78] shadow-lg',
            photoInner: 'flex min-h-96 flex-col items-end justify-start rounded-[1.3rem] bg-[radial-gradient(circle_at_top,#f7ebe2_0%,#e9c7b2_35%,#bd8166_100%)] p-6',
            rightPanel: 'rounded-[1.75rem] bg-[#fbf6ee] p-5 md:p-7',
            eyebrow: 'text-[#9a6b42]',
            namePill: 'rounded-full border border-[#b99b7f] px-5 py-2 text-sm text-[#5e4030]',
            heading: 'A little scrapbook of who I am',
            headingClass: 'text-[#3b2416]',
            body: 'text-[#5c4030]',
            intro:
                "I'm Shagun Gupta, a BCA student and passionate web developer from Uttar Pradesh. I love creating responsive websites and full-stack applications, and I'm always excited to learn, experiment, and build projects that solve real-world problems.",
            quickCard: 'rounded-3xl bg-white p-5 shadow-[0_12px_30px_rgba(89,57,35,0.08)]',
            quickItem: 'rounded-2xl bg-[#f8efe1] px-4 py-3 text-[#5c4030]',
            skillsCard: 'rounded-3xl border border-[#dfc7b0] bg-[#fffaf2] p-5',
            noteCard: 'rotate-[-2deg] rounded-3xl bg-[#e7d1bf] p-3 shadow-[0_12px_30px_rgba(89,57,35,0.08)]',
            noteInner: 'rounded-[1.2rem] border-4 border-white bg-[linear-gradient(135deg,#dcb8a2,#f2dfd1,#c5886b)] p-4',
            noteStage: 'flex min-h-48 items-end rounded-[0.9rem] bg-[radial-gradient(circle_at_top,#f8eee6_0%,#ebc7b4_38%,#ad7157_100%)] p-4',
            noteBubble: 'max-w-44 bg-white/80 px-3 py-2 text-sm leading-6 text-[#5e4030]',
            notes: [
                'BCA student from Uttar Pradesh',
                'Passionate about full-stack development',
                'Loves building clean, responsive websites',
                'Enjoys turning ideas into real projects',
            ],
            favorites: [
                'UI design details',
                'Project building',
                'Learning new tools',
                'Problem solving',
            ],
            noteText: 'Add a second casual photo here for the exact moodboard style.',
        },
        skills: {
            section: 'relative overflow-hidden bg-[#f8ecdd] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-[2rem] border border-[#dfc7ad] bg-[#fcf5ea] p-5 shadow-[0_20px_60px_rgba(89,57,35,0.12)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] bg-[#f1ddd8] p-5 md:p-6',
            eyebrow: 'text-[#9b654f]',
            heading: 'The tools I use to bring ideas to life',
            headingClass: 'text-[#3b2416]',
            body: 'text-[#5c4030]',
            highlight: 'rounded-[1.35rem] border border-[#e5c8b5] bg-[#fffaf3] px-4 py-4 text-[#5c4030] shadow-[0_10px_24px_rgba(89,57,35,0.06)]',
            learningCard: 'mt-6 rotate-[-2deg] rounded-[1.5rem] bg-[#e7d1bf] p-3 shadow-[0_12px_30px_rgba(89,57,35,0.08)]',
            learningInner: 'rounded-[1.2rem] border-4 border-white bg-[linear-gradient(135deg,#e7c4b9,#f4e6d8,#d9ab90)] p-4',
            learningPill: 'rounded-full bg-white/80 px-4 py-2 text-sm text-[#5e4030]',
            groupCard: [
                'rounded-[1.65rem] border border-[#e8b8c6] bg-[#f5d7df] p-5 md:p-6',
                'rounded-[1.65rem] border border-[#dfc19b] bg-[#f4e4d0] p-5 md:p-6',
                'rounded-[1.65rem] border border-[#d9c7b0] bg-[#efe6d8] p-5 md:p-6',
            ],
            groupTitle: 'text-[#3d2819]',
            groupBadge: 'rounded-full border border-white/70 bg-white/70 px-4 py-2 text-xs uppercase tracking-[0.3em] text-[#7b5642]',
            skillPill: 'rounded-full border border-white/80 bg-[#fff9f1] px-4 py-2 text-sm text-[#5c4030] shadow-[0_8px_18px_rgba(89,57,35,0.06)]',
            intro:
                'I enjoy building projects from interface to logic. My focus is on creating responsive, user-friendly web experiences while steadily growing stronger in full-stack development.',
            strengths: [
                'Responsive website development',
                'Clean and readable UI structure',
                'Full-stack project building',
                'Fast learner with a builder mindset',
            ],
            learningNow: ['Advanced React patterns', 'Backend architecture', 'UI polish and animation'],
        },
        projects: {
            section: 'relative overflow-hidden bg-[#f6e7d6] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-[2rem] border border-[#dcc1a5] bg-[#fcf4e9] p-5 shadow-[0_20px_60px_rgba(89,57,35,0.12)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] bg-[#f0dbd2] p-5 md:p-6',
            eyebrow: 'text-[#9a654b]',
            heading: "A few things I've been building",
            headingClass: 'text-[#3b2416]',
            body: 'text-[#5c4030]',
            highlight: 'rounded-[1.35rem] border border-[#e4c8b3] bg-[#fffaf3] px-4 py-4 text-[#5c4030] shadow-[0_10px_24px_rgba(89,57,35,0.06)]',
            focusCard: 'mt-6 rotate-[2deg] rounded-[1.45rem] bg-[#e7d0bd] p-3 shadow-[0_12px_30px_rgba(89,57,35,0.08)]',
            focusInner: 'rounded-[1.2rem] border-4 border-white bg-[linear-gradient(135deg,#edcabc,#f6eadf,#d7a98e)] p-4',
            cardTone: [
                'rounded-[1.7rem] border border-[#c9a87c] bg-[#ede0cc] p-5 md:p-6',
                'rounded-[1.7rem] border border-[#e8b6c5] bg-[#f5d8df] p-5 md:p-6',
            ],
            badge: 'rounded-full border border-white/70 bg-white/75 px-4 py-2 text-xs uppercase tracking-[0.28em] text-[#7b5642]',
            title: 'text-[#3d2819]',
            tag: 'rounded-full border border-white/80 bg-[#fff9f1] px-4 py-2 text-sm text-[#5c4030] shadow-[0_8px_18px_rgba(89,57,35,0.06)]',
            primaryCta: 'rounded-full bg-[#3b2416] px-5 py-3 text-sm text-[#fff6eb] transition duration-300 hover:bg-[#573726]',
            secondaryCta: 'rounded-full border border-[#8f6850] px-5 py-3 text-sm text-[#5c4030] transition duration-300 hover:bg-white/60',
            intro:
                'These projects reflect how I like to learn by building. I enjoy combining clean design, practical features, and responsive development to create work that feels useful and polished.',
            highlights: [
                'Responsive design across screen sizes',
                'Thoughtful UI layout and visual consistency',
                'Practical full-stack experimentation',
            ],
            focusText:
                "I'm especially interested in projects that let me shape both the look and the logic of a product.",
        },
        contact: {
            section: 'relative overflow-hidden bg-[#f3e1cd] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-4xl border border-[#dcc1a6] bg-[#fbf2e7] p-5 shadow-[0_20px_60px_rgba(89,57,35,0.12)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] bg-[#f0dbd2] p-5 md:p-6',
            rightPanel: 'rounded-[1.75rem] bg-[#fffaf3] p-5 shadow-[0_12px_30px_rgba(89,57,35,0.08)] md:p-6',
            eyebrow: 'text-[#9a654b]',
            heading: "Let's build something thoughtful together",
            headingClass: 'text-[#3b2416]',
            body: 'text-[#5c4030]',
            card: 'rounded-[1.45rem] border p-4 shadow-[0_10px_24px_rgba(89,57,35,0.06)]',
            noteCard: 'mt-6 -rotate-2 rounded-3xl bg-[#e7d0bd] p-3 shadow-[0_12px_30px_rgba(89,57,35,0.08)]',
            noteInner: 'rounded-[1.2rem] border-4 border-white bg-[linear-gradient(135deg,#e8c5b7,#f5e9dd,#d6a98e)] p-4',
            pill: 'rounded-full border border-[#cba98b] px-4 py-2 text-xs uppercase tracking-[0.28em] text-[#7b5642]',
            label: 'text-[#7b5642]',
            inputBase: 'w-full rounded-[1.2rem] border bg-white/90 px-4 py-3 text-[#5c4030] outline-none transition focus:bg-white focus:ring-2 focus:ring-[#f1d4bc]',
            inputOk: 'border-[#dfc7b0] focus:border-[#b98a6c]',
            footer: 'flex flex-wrap items-center justify-between gap-4 rounded-[1.6rem] border border-[#ead8c7] bg-[linear-gradient(135deg,#fbf2e6,#fff8f2)] px-4 py-4 shadow-[0_10px_24px_rgba(89,57,35,0.04)]',
            submit: 'rounded-full bg-[#3b2416] px-6 py-3 text-sm text-[#fff6eb] transition duration-300 hover:bg-[#573726] disabled:cursor-not-allowed disabled:opacity-70',
            intro:
                'If you have a project idea, internship opportunity, or just want to connect, this is the best place to start. I enjoy working on experiences that feel clean, useful, and visually well crafted.',
            noteText:
                'This form is now connected to your backend route and can send messages directly to your email setup.',
        },
    },
    professional: {
        hero: {
            section: 'relative overflow-hidden bg-[radial-gradient(circle_at_top,#172554_0%,#0f172a_44%,#020617_100%)] px-5 pb-16 pt-28 md:px-8 md:pt-32',
            backgroundWord: 'text-white/6',
            badge:
                'inline-flex items-center gap-3 rounded-full border border-white/12 bg-white/6 px-4 py-2 shadow-[0_12px_30px_rgba(2,6,23,0.36)] backdrop-blur-sm',
            badgeDot: 'bg-[#38bdf8]',
            badgeText: 'text-slate-300',
            eyebrow: 'text-sky-300',
            heading: 'text-white',
            headingAccent: 'text-slate-300',
            body: 'text-slate-300',
            tag: 'rounded-full border border-white/12 bg-white/6 px-4 py-2 text-sm text-slate-200 shadow-[0_14px_34px_rgba(2,6,23,0.22)]',
            primaryCta:
                'rounded-full bg-[#38bdf8] px-6 py-3 text-sm font-semibold text-[#082f49] transition duration-300 hover:bg-[#7dd3fc]',
            secondaryCta:
                'rounded-full border border-white/12 bg-white/4 px-6 py-3 text-sm text-slate-200 transition duration-300 hover:bg-white/8',
            mediaWrap:
                'relative overflow-hidden rounded-4xl border border-white/12 bg-[linear-gradient(180deg,#0f172a_0%,#111827_42%,#1d4ed8_100%)] p-4 shadow-[0_24px_54px_rgba(2,6,23,0.45)]',
            mediaInner:
                'rounded-[1.7rem] border border-white/12 bg-[radial-gradient(circle_at_top,#0f172a_0%,#111827_42%,#1e3a8a_100%)] p-3',
            infoCardOne: 'rounded-[1.8rem] border border-white/10 bg-white/6 p-5 shadow-[0_14px_34px_rgba(2,6,23,0.28)]',
            infoCardTwo: 'rounded-[1.8rem] border border-white/10 bg-[#0f172a]/78 p-5 shadow-[0_14px_34px_rgba(2,6,23,0.28)]',
            infoEyebrow: 'text-sky-300',
            infoHeading: 'text-white',
            softBlobOne: 'bg-sky-400/18',
            softBlobTwo: 'bg-blue-500/16',
            softBlobThree: 'bg-cyan-300/12',
            role: 'Frontend Developer / React Builder',
            title: 'Full Stack Developer ',
            titleLines: [' focused on building real-world MERN apps-', 'from database design to deployed frontend.'],
            description:
                "I'm Shagun Gupta, a web developer focused on building responsive React experiences with clean structure, practical UX decisions, and a stronger engineering mindset.",
            cards: [
                'Responsive React interfaces',
                'Structured component thinking',
                'Professional portfolio presentation',
            ],
            sideTitle: 'Focus Area',
            sideValue: 'Frontend Engineering',
            noteTitle: 'Developer Note',
            noteValue:
                'I enjoy translating product ideas into interfaces that feel clear, fast, and dependable.',
        },
        about: {
            section: 'relative overflow-hidden bg-[#020617] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-4xl border border-white/10 bg-[#0f172a] p-4 shadow-[0_20px_60px_rgba(2,6,23,0.42)] md:p-6 lg:p-8',
            leftPanel: 'relative rounded-[1.75rem] border border-white/10 bg-[linear-gradient(180deg,#111827_0%,#172554_100%)] p-4 md:p-5',
            titleMark: 'text-sky-300/60',
            photoFrame: 'relative z-20 mt-48 rounded-3xl border border-white/10 bg-[linear-gradient(135deg,#0f172a,#1e293b,#1d4ed8)] shadow-lg',
            photoInner: 'flex min-h-96 flex-col items-end justify-start rounded-[1.3rem] bg-[radial-gradient(circle_at_top,#0f172a_0%,#172554_35%,#1d4ed8_100%)] p-6',
            rightPanel: 'rounded-[1.75rem] border border-white/10 bg-[#111827] p-5 md:p-7',
            eyebrow: 'text-sky-300',
            namePill: 'rounded-full border border-white/12 bg-white/4 px-5 py-2 text-sm text-slate-200',
            heading: 'The developer behind the interface',
            headingClass: 'text-white',
            body: 'text-slate-300',
            intro:
                "I'm Shagun Gupta, a frontend-focused developer building my full-stack foundation through practical projects. I care about clean code, responsive systems, and interfaces that communicate clearly.",
            quickCard: 'rounded-3xl border border-white/10 bg-[#0b1220] p-5 shadow-[0_12px_30px_rgba(2,6,23,0.25)]',
            quickItem: 'rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-slate-200',
            skillsCard: 'rounded-3xl border border-white/10 bg-[#0b1220] p-5',
            noteCard: 'rounded-3xl border border-white/10 bg-[linear-gradient(135deg,#0f172a,#172554)] p-3 shadow-[0_12px_30px_rgba(2,6,23,0.28)]',
            noteInner: 'rounded-[1.2rem] border border-white/10 bg-[linear-gradient(135deg,#111827,#1e293b,#1d4ed8)] p-4',
            noteStage: 'flex min-h-48 items-end rounded-[0.9rem] border border-white/10 bg-[radial-gradient(circle_at_top,#0f172a_0%,#172554_38%,#1e40af_100%)] p-4',
            noteBubble: 'max-w-52 rounded-2xl border border-white/10 bg-white/10 px-3 py-2 text-sm leading-6 text-slate-200',
            notes: [
                'Frontend-first portfolio mindset',
                'Actively strengthening React and backend depth',
                'Comfortable with responsive implementation',
                'Focused on practical, real-project learning',
            ],
            favorites: [
                'Component structure',
                'UI refinement',
                'Problem solving',
                'Shipping projects',
            ],
            noteText: 'This section now presents you more like a developer profile than a moodboard.',
        },
        skills: {
            section: 'relative overflow-hidden bg-[#020617] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-[2rem] border border-white/10 bg-[#0f172a] p-5 shadow-[0_20px_60px_rgba(2,6,23,0.42)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] border border-white/10 bg-[linear-gradient(180deg,#111827_0%,#172554_100%)] p-5 md:p-6',
            eyebrow: 'text-sky-300',
            heading: 'Core skills for modern web development',
            headingClass: 'text-white',
            body: 'text-slate-300',
            highlight: 'rounded-[1.35rem] border border-white/10 bg-white/5 px-4 py-4 text-slate-200 shadow-[0_10px_24px_rgba(2,6,23,0.18)]',
            learningCard: 'mt-6 rounded-[1.5rem] border border-white/10 bg-[linear-gradient(135deg,#0f172a,#172554)] p-3 shadow-[0_12px_30px_rgba(2,6,23,0.26)]',
            learningInner: 'rounded-[1.2rem] border border-white/10 bg-[linear-gradient(135deg,#111827,#1e293b,#1d4ed8)] p-4',
            learningPill: 'rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm text-slate-200',
            groupCard: [
                'rounded-[1.65rem] border border-sky-400/18 bg-sky-400/8 p-5 md:p-6',
                'rounded-[1.65rem] border border-blue-400/18 bg-blue-400/8 p-5 md:p-6',
                'rounded-[1.65rem] border border-slate-400/18 bg-slate-400/8 p-5 md:p-6',
            ],
            groupTitle: 'text-white',
            groupBadge: 'rounded-full border border-white/10 bg-white/8 px-4 py-2 text-xs uppercase tracking-[0.3em] text-slate-300',
            skillPill: 'rounded-full border border-white/10 bg-white/8 px-4 py-2 text-sm text-slate-100 shadow-[0_8px_18px_rgba(2,6,23,0.16)]',
            intro:
                'My current stack is centered on frontend delivery, responsive UI engineering, and practical full-stack project development with a strong learning curve.',
            strengths: [
                'React-based interface development',
                'Responsive, mobile-aware implementation',
                'REST API and backend integration',
                'Consistent component-driven thinking',
            ],
            learningNow: ['Advanced React patterns', 'Backend architecture', 'Performance and accessibility'],
        },
        projects: {
            section: 'relative overflow-hidden bg-[#020617] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-[2rem] border border-white/10 bg-[#0f172a] p-5 shadow-[0_20px_60px_rgba(2,6,23,0.42)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] border border-white/10 bg-[linear-gradient(180deg,#111827_0%,#172554_100%)] p-5 md:p-6',
            eyebrow: 'text-sky-300',
            heading: 'Selected projects with product and frontend focus',
            headingClass: 'text-white',
            body: 'text-slate-300',
            highlight: 'rounded-[1.35rem] border border-white/10 bg-white/5 px-4 py-4 text-slate-200 shadow-[0_10px_24px_rgba(2,6,23,0.18)]',
            focusCard: 'mt-6 rounded-[1.45rem] border border-white/10 bg-[linear-gradient(135deg,#0f172a,#172554)] p-3 shadow-[0_12px_30px_rgba(2,6,23,0.26)]',
            focusInner: 'rounded-[1.2rem] border border-white/10 bg-[linear-gradient(135deg,#111827,#1e293b,#1d4ed8)] p-4',
            cardTone: [
                'rounded-[1.7rem] border border-sky-400/20 bg-sky-400/8 p-5 md:p-6',
                'rounded-[1.7rem] border border-blue-400/20 bg-blue-400/8 p-5 md:p-6',
            ],
            badge: 'rounded-full border border-white/10 bg-white/8 px-4 py-2 text-xs uppercase tracking-[0.28em] text-slate-300',
            title: 'text-white',
            tag: 'rounded-full border border-white/10 bg-white/8 px-4 py-2 text-sm text-slate-200 shadow-[0_8px_18px_rgba(2,6,23,0.14)]',
            primaryCta: 'rounded-full bg-[#38bdf8] px-5 py-3 text-sm font-semibold text-[#082f49] transition duration-300 hover:bg-[#7dd3fc]',
            secondaryCta: 'rounded-full border border-white/10 px-5 py-3 text-sm text-slate-200 transition duration-300 hover:bg-white/8',
            intro:
                'These projects show how I approach frontend implementation, UI direction, and hands-on full-stack learning through real builds.',
            highlights: [
                'Product-oriented frontend implementation',
                'Clear visual hierarchy and responsive behavior',
                'Practical integration across UI and backend',
            ],
            focusText:
                'The goal is to present myself less like a student showcase and more like an emerging professional developer.',
        },
        contact: {
            section: 'relative overflow-hidden bg-[#020617] px-5 py-20 md:px-8',
            shell: 'mx-auto max-w-6xl rounded-4xl border border-white/10 bg-[#0f172a] p-5 shadow-[0_20px_60px_rgba(2,6,23,0.42)] md:p-7 lg:p-8',
            leftPanel: 'rounded-[1.75rem] border border-white/10 bg-[linear-gradient(180deg,#111827_0%,#172554_100%)] p-5 md:p-6',
            rightPanel: 'rounded-[1.75rem] border border-white/10 bg-[#111827] p-5 shadow-[0_12px_30px_rgba(2,6,23,0.24)] md:p-6',
            eyebrow: 'text-sky-300',
            heading: 'Open to professional conversations and collaborations',
            headingClass: 'text-white',
            body: 'text-slate-300',
            card: 'rounded-[1.45rem] border border-white/10 p-4 shadow-[0_10px_24px_rgba(2,6,23,0.18)]',
            noteCard: 'mt-6 rounded-3xl border border-white/10 bg-[linear-gradient(135deg,#0f172a,#172554)] p-3 shadow-[0_12px_30px_rgba(2,6,23,0.26)]',
            noteInner: 'rounded-[1.2rem] border border-white/10 bg-[linear-gradient(135deg,#111827,#1e293b,#1d4ed8)] p-4',
            pill: 'rounded-full border border-white/10 bg-white/8 px-4 py-2 text-xs uppercase tracking-[0.28em] text-slate-300',
            label: 'text-slate-300',
            inputBase: 'w-full rounded-[1.2rem] border bg-white/6 px-4 py-3 text-slate-100 outline-none transition focus:bg-white/10 focus:ring-2 focus:ring-sky-400/30',
            inputOk: 'border-white/10 focus:border-sky-400/50',
            footer: 'flex flex-wrap items-center justify-between gap-4 rounded-[1.6rem] border border-white/10 bg-[linear-gradient(135deg,#0f172a,#111827)] px-4 py-4 shadow-[0_10px_24px_rgba(2,6,23,0.14)]',
            submit: 'rounded-full bg-[#38bdf8] px-6 py-3 text-sm font-semibold text-[#082f49] transition duration-300 hover:bg-[#7dd3fc] disabled:cursor-not-allowed disabled:opacity-70',
            intro:
                'Whether it is an internship, freelance assignment, or project discussion, I would love to hear about work that values clean frontend execution and thoughtful product experience.',
            noteText:
                'Professional mode reframes this section more like a reliable developer contact surface.',
        },
    },
}